### ISSUE TITLE
Add step to convert simulated SCE to AnnData

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/OpenScPCA-nf#47]
Right now in the simulate module we only output the simulated SCE objects. This means that when someone downloads test data using the `download-data.py` script in `OpenScPCA-analysis`, the only available test data is as an SCE object. I can imagine there are cases where people will want the same test data but as an AnnData object. This step already exists in the `simulate-sce` module in the analysis repo, but doesn't exist here. 

We should add a step to the simulate workflow to run the script to convert the SCE objects to AnnData.

**Comment by jashapiro** [comment]
It should definitely exist here too! I thought it was there, and I have the script here already. I must have just never added it during testing.

**Comment by jashapiro** [comment]
The script is called, but we are missing the step to move the processed data to match the expected format. https://github.com/AlexsLemonade/OpenScPCA-nf/blob/700bbb6c2ef5ab30333550289bf7ef86b12e678e/modules/simulate-sce/main.nf#L54

I confirmed that they are present with:
```
aws s3 ls s3://openscpca-test-data-release-public-access/test/SCPCP000001/ --recursive --no-sign-request
```

Are the files not getting downloaded as expected?

Leaving this open because we probably do want to match the real processed h5ad files.

**Comment by allyhawkins** [comment]
Just confirming that using `--format anndata` works for download. I had missed seeing the line where the script is run so was confused. This is all good other than the formats not matching.
